# Generated by Django 4.1 on 2022-08-11 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("traits", "0003_remove_trait_animals"),
        ("groups", "0002_alter_group_name_alter_group_scientific_name"),
        ("animals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="traits",
            field=models.ManyToManyField(related_name="animal", to="traits.trait"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animals",
                to="groups.group",
            ),
        ),
    ]
