# Generated by Django 4.1 on 2022-08-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traits", "0004_alter_trait_name"),
        ("animals", "0003_alter_animal_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="traits",
            field=models.ManyToManyField(related_name="animals", to="traits.trait"),
        ),
    ]
