# Generated by Django 4.1 on 2022-08-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trait",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
