# Generated by Django 4.1 on 2022-08-11 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traits", "0002_alter_trait_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trait",
            name="animals",
        ),
    ]
